import { ThemeProvider } from "@components/providers";
import "app/globals.css";

export const metadata = {
  title: "Themes",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="bg-th-background h-full">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
